### ISSUE TITLE
Bug: cannot import `deno2node`

### ISSUE THREAD

**Issue by TillaTheHun0** [fromdeno/deno2node#37]
Heya. Thanks for this awesome tool. 

I am seeing an error when importing `deno2node`

```
Warning Implicitly using latest version (0.178.0) for https://deno.land/std/node/path.tsiB (8/12)
error: Module not found "https://deno.land/std/node/path.ts".
    at https://deno.land/x/deno2node@v1.7.1/src/context.ts:1:18
```

Looks to be an implicit import is expecting an export that is no longer there in the latest version.

Steps to reproduce:

```
deno run https://deno.land/x/deno2node@v1.7.1/src/context.ts
```

Looks like the functionality has been replicated on Deno's `path` https://deno.land/std@0.178.0/path/mod.ts, so could use that instead.

**Comment by wojpawlik** [comment]
Ideally, https://github.com/fromdeno/deno2node/blob/main/scripts/pretest.ts should keep the specifier in sync with what x/ts_morph depends on.
